name: Deploy to InfinityFree

on:
  push:
    branches:
      - master   

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Deploy por FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /htdocs/
